# ~/.config/hypr/hyprtoolkit.conf

# Colors
background_color = 0xFF1E1E2E
base_color       = 0xFF181825
text_color       = 0xFFCDD6F4
alt_base_color   = 0xFF313244
bright_text_color= 0xFFF5E0DC
accent_color     = 0xFF89B4FA
sec_accent_color = 0xFFF5C2E7

# Fonts
font_family = Sans
monospace_font_family = Monospace
font_size_regular = 10


