# ~/.config/hypr/hypridle.conf

general {
    lock_cmd = pidof hyprlock || hyprlock       # Avoids starting multiple lock instances
    before_sleep_cmd = loginctl lock-session    # Locks session before your PC goes to sleep
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' # Turn the display back on after waking up

}

# 1. Dim monitor backlight (2 min)
listener {
    timeout = 120
    on-timeout = ddcutil setvcp 10 10
    on-resume = ddcutil setvcp 10 100
}

# 3. Lock screen (5 min)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 4. Turn off screen completely (10 min)
listener {
    timeout = 600
    # 04 means power off / standby for feature D6
    on-timeout = ddcutil setvcp D6 04 
    # 01 means DPM on / normal operation
    on-resume = ddcutil setvcp D6 01
}

# 5. Suspend PC (15 min)
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
